### PR TITLE
Update app to v1.72.173-1

### PR DESCRIPTION
**Pull request by Salvoxia**
This pull request updates the app to v1.72.173-1
* Use Debian Bookworm
* The installation path inside the container changed slightly, all paths have been updated in Dockerfile and README
* Added upgrading instructions to README to update bind mounts
* Updated instructions for mounting and configuring shutdown script to adhere to new restrictions by IPP

### CODE REVIEW

**Comment by Mavyre** [comment]
Awesome, I didn't knew there was a new version of IPP out (doesn't happen much lately). 

About the curl command, is it really mendatory to pass a User Agent?

**Comment by Salvoxia** [comment]
Yeah, I tried it first by simply updating the download URL in your original file, curl will throw an error. Looks like Eaton put a safeguard in there.

Without user agent:
```
 curl -L https://www.eaton.com/content/dam/eaton/products/backup-power-ups-surge-it-power-distribution/power-management-software-connectivity/eaton-intelligent-power-protector/software/ippv1-72/ipp-linux_1.72.173-1_amd64.deb -o ipp.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

With user agent:
```
curl -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edge/116.0.1938.69" https://www.eaton.com/content/dam/eaton/products/backup-power-ups-surge-it-power-distribution/power-management-software-connectivity/eaton-intelligent-power-protector/software/ippv1-72/ipp-linux_1.72.173-1_amd64.deb -o ipp.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6056k  100 6056k    0     0  7337k      0 --:--:-- --:--:-- --:--:-- 7341k
```

**Comment by Mavyre** [comment]
Useless and easy bypassable safeguards, as always...

**Comment by Mavyre** [comment]
New version has been pushed to Docker hub. Thanks for the contribution!

**Pull request merged**
